[package]
name = "storage"
version = "0.1.0"
edition = "2024"

[dependencies]
beskar-core = { workspace = true }
hashbrown = { version = "0.16.1" }
hyperdrive = { workspace = true }
thiserror = { workspace = true }
