[package]
name = "bashkar"
version = "0.1.0"
edition = "2024"

[dependencies]
ascii-ui = { path = "../ascii-ui" }
beskar-core = { workspace = true }
beskar-lib = { workspace = true }
hyperdrive = { workspace = true }
