[package]
name = "doom"
version = "0.1.0"
edition = "2024"

[dependencies]
beskar-core = { workspace = true }
beskar-lib = { workspace = true }
hyperdrive = { workspace = true }

[build-dependencies]
cc = "1.2.54"
